---
- name: Deploy Web App
  hosts: localhost
  connection: local
  become: yes
  become_user: ansible

  vars:
    p_name: "{{ lookup('env','prodadmin_name') }}"
    p_pass: "{{ lookup('env','prodadmin_password') }}"2
    md5_url: "http://34.86.155.6:8081/repository/my-web-project/com/efsavage/hello-world-war/1.0.0/hello-world-war-1.0.0.war.md5"
    md5_value: "{{ lookup('url', md5_url, username=p_name, password=p_pass) }}"
  tasks:
  
  - name: md5file
    stat:
      path: /opt/tomcat/webapps/websiteisdown.war
      get_md5: yes
    register: existing_file

  - debug:
      msg: "{{ existing_file.stat.md5 }}"
    when: existing_file.stat.exists

  - name: set force
    set_fact:
      force_new_download: "{{ existing_file.stat.md5 != md5_value }}"
    when: existing_file.stat.exists

  - name: Download package repository
    get_url:
      url: http://34.86.155.6:8081/repository/my-web-project/com/efsavage/hello-world-war/1.0.0/hello-world-war-1.0.0.war
      url_username: "{{ p_name }}"
      url_password: "{{ p_pass }}"
      dest: /opt/tomcat/webapps/websiteisdown.war
      checksum: "md5:{{ md5_value }}"
      force: "{{ force_new_download | default ('false') }}"
      mode: '0664'

  - name: Stop tomcat
    shell: /opt/tomcat/bin/shutdown.sh

  - name: Start tomcat
    shell: /opt/tomcat/bin/startup.sh
